---
resources:
- name: hello
  type: git
  source:
    uri: https://github.com/making/hello-concourse.git  
- name: result
  type: git
  source:
    uri: git@gist.github.com/making/dbc56fbd08f415fa52c784f4cd2e4bd3
    private_key: {{github-private-key}}

jobs: 
- name: job-hello
  public: true
  plan:
  - get: hello	
    trigger: true
  - get: result
  - task: run-hello
    file: hello/hello.yml
  - task: commit-log
    file: hello/commit-log.yml
  - put: result
    params:
      repository: updated-result
